server:
  port: 8513

spring:
  application:
    name: service-cart
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  data:
    redis:
      host: 8.130.176.200
      port: 8009